# Generated by Django 4.0 on 2021-12-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appContatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbtabcategoria',
            old_name='nome',
            new_name='varNome',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='strDataCriacao',
            new_name='varDataCriacao',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='strEmail',
            new_name='varEmail',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='keyTabCategoria',
            new_name='varKeyTabCategoria',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='strNome',
            new_name='varNome',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='strSobreNome',
            new_name='varSobreNome',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='TexDescricao',
            new_name='varTexDescricao',
        ),
    ]
