# Generated by Django 4.0 on 2021-12-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appContatos', '0002_rename_nome_dbtabcategoria_varnome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbtabcategoria',
            old_name='varNome',
            new_name='strNome',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='varDataCriacao',
            new_name='strDataCriacao',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='varEmail',
            new_name='strEmail',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='varKeyTabCategoria',
            new_name='strKeyTabCategoria',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='varNome',
            new_name='strNome',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='varSobreNome',
            new_name='strSobreNome',
        ),
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='varTexDescricao',
            new_name='texDescricao',
        ),
    ]
