# Generated by Django 4.0 on 2021-12-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContatos', '0004_dbtabcontatos_strtelefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtabcontatos',
            name='BoolExibir',
            field=models.BooleanField(default=True),
        ),
    ]
