# Generated by Django 4.0 on 2021-12-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContatos', '0006_remove_dbtabcontatos_boolexibir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtabcontatos',
            name='ImgFoto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m'),
        ),
    ]
