# Generated by Django 4.0 on 2021-12-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appContatos', '0007_dbtabcontatos_imgfoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbtabcontatos',
            old_name='ImgFoto',
            new_name='imgFoto',
        ),
    ]
