"""
Django settings for agendaContatos project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
# Mensagens
# ALERTAS SISTEMA
from django.contrib.messages import constants
# PROCURAR abaixo a constante:
# MESSAGE_TAGS
# 
from pathlib import Path
# 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
# 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n6aat8i4h!!(=@)bx6a#0xkd)!5+5tf(bd-u(%h)*q3%^^o03*'
# 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# 
ALLOWED_HOSTS = ['127.0.0.1', 'www.habilidade.com', 'habilidade.com', '192.168.0.179'] # www.habilidade.com
# 
# Application definition
# 
INSTALLED_APPS = [
    # → Aqui registra o app do comando: 
    # → python manage.py startapp [APP_PROJETO]
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appContatos.apps.AppcontatosConfig',
    # → ATENÇÃO ao ↑ .apps.
    'appUsuarios.apps.AppusuariosConfig',
]
# 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# 
ROOT_URLCONF = 'agendaContatos.urls'
# 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # → Registra a pasta principal do Template
        # → Com arquivo base
        # → Com parciais - Head, Menu, Rodapé, etc... 
        # → Com statics - Vendor/bootstrap, js, etc... 
        # → --- [BASE_DIR / 'djTemplates']
        'DIRS': [BASE_DIR / 'djTemplates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# 
WSGI_APPLICATION = 'agendaContatos.wsgi.application'
# 
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
# 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'habilidade03',
        'USER': 'habilida03_add2',
        'PASSWORD': 'dudu1998',
        'HOST': 'mysql08-farm1.kinghost.net',
        'PORT': '3306',
    }
}
# 
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
# 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# 
# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
# 
# Mudar a liguagem do Sistema
# -------------------- ↓ - ↓ ---------
# De: LANGUAGE_CODE = 'en-us' Para:
LANGUAGE_CODE = 'pt-br'
# Mudar o fuso-horário do Sistema:
# ----------------- ↓ ----------------
# De: TIME_ZONE = 'UTC' Para: 
TIME_ZONE = 'America/Sao_Paulo'
# 
USE_I18N = True
# 
USE_TZ = True
# 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
# 
STATIC_URL = 'static/'
# ↓ Para puxar o {%load static%}
STATICFILES_DIRS = [
    BASE_DIR / 'djTemplates/static', 
]
# 
# Para o DEPLOY 
STATIC_ROOT = BASE_DIR / 'static'
# Após a criação desta constante, digite:
# python manage.py collectstatic
# 
# Alteração para pasta UPLOAD de imagens:
MEDIA_ROOT = BASE_DIR / 'upload'
MEDIA_URL = 'upload/'
# Após a inclusão desta alteração crie um campo: foto
# models.ImageField(blank=True)
# 
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
# 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 
# Mensagens
# ALERTAS SISTEMA
# 
MESSAGE_TAGS = {
    constants.ERROR: 'alert-danger', 
    constants.WARNING: 'alert-warning',  
    constants.SUCCESS: 'alert-success', 
    constants.INFO: 'alert-info', 
}
# Vá para a configuração na view
